# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('utils', './utils'),
        ('config', './config'),
        ('crawlers', './crawlers'),
        ('ui', './ui'),
        ('analysis', './analysis'),
        ('database', './database'),
        ('models', './models'),
    ],
    hiddenimports=[
        'pkg_resources.extern',
        'json5',
        'winsdk',
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.sip',
        'selenium',
        'selenium.webdriver.chrome.service',
        'numpy',
        'urllib3',
        'torch',
        'torch._C',
        'torchvision',
        'openpyxl',
        'multiprocessing',
        'multiprocessing.pool',
        'multiprocessing.managers',
        'multiprocessing.popen_spawn_win32', 
        'concurrent.futures',
        'transformers',
        'transformers.pipelines',
        'transformers.generation',
        'transformers.generation.utils',
        'transformers.models.auto',
        'huggingface_hub',
        'tokenizers',
        'safetensors',
        'sqlite3',
        'undetected_chromedriver',
        'sklearn',
        'sklearn.base',
        'sklearn.utils',
        'sklearn.utils._isfinite',
        'sklearn._cyutility',
        'sklearn.metrics',
        'sklearn.metrics.roc_curve',
        'joblib',
        'threadpoolctl',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='main',
)